version: "3"
services:
  app-cubes:
    container_name: app-cubes
    build:
      context: .
      dockerfile: .Dockerfile
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://${DB_USER}:${DB_PASSWORD}@${DB_CONNECTION}:${DB_PORT}/${DB_DATABASE}
      NODE_ENV: development
      PORT: ${APP_PORT}
    ports:
      - "${APP_PORT}:${APP_PORT}"
  postgres:
    container_name: postgres
    image: postgres:10.4
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes: 
      - ./postgresdata:/var/lib/postgresql/data
      - ./src/migrations/dbinit.sql:/docker-entrypoint-initdb.d/dbinit.sql
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:4.18
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGA_MAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGA_PASSWORD}
      PGADMIN_LISTEN_PORT: ${PGA_LISTEN_PORT}
    ports:
      - "${PGA_PORT}:${PGA_LISTEN_PORT}"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      - postgres
volumes:
    db-data:
    pgadmin-data: