version: "3"
services:

  postgres:
    container_name: postgres
    image: postgres:14.1-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes: 
      - volume_postgres:/var/lib/mysql
      - ./.docker/db/cubes.sql:/docker-entrypoint-initdb.d/cubes.sql

  app-cubes:
    container_name: app-cubes
    build:
      context: .
      dockerfile: .Dockerfile
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://postgres:postgres@${DB_CONNECTION}:${DB_PORT}/${DB_DATABASE}
      NODE_ENV: development
      PORT: ${APP_PORT}
      DB_HOST: postgres
      DB_PORT: ${APP_PORT}
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: lfc_db
    ports:
      - "${APP_PORT}:${APP_PORT}"

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:6.0
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: lefebvre@antadis.com
      PGADMIN_DEFAULT_PASSWORD: SuperSecret
      PGADMIN_LISTEN_PORT: ${PGA_LISTEN_PORT}
    ports:
      - "${PGA_PORT}:${PGA_LISTEN_PORT}"
    volumes:
      - volume_pgadmin:/var/lib/pgadmin
    depends_on:
      - postgres

volumes:
    volume_postgres:
      driver: local
    volume_pgadmin: