version: "3"
services:
  postgres:
    container_name: postgres
    image: postgres:14.1-alpine
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes: 
      - volume_postgres:/var/lib/mysql
      - ./.docker/db/cubes.sql:/docker-entrypoint-initdb.d/cubes.sql
  app-cubes:
    container_name: app-cubes
    build:
      context: .
      dockerfile: .Dockerfile
    depends_on:
      - postgres
    environment:
      NODE_ENV: development
      PORT: ${APP_PORT}
    ports:
      - "${APP_PORT}:${APP_PORT}"
    volumes:
      - ${VOLUME_PATH_APP}
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:6.0
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGA_MAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGA_PASSWORD}
      PGADMIN_LISTEN_PORT: ${PGA_LISTEN_PORT}
    ports:
      - "${PGA_PORT}:${PGA_LISTEN_PORT}"
    volumes:
      - volume_pgadmin:/var/lib/pgadmin
    depends_on:
      - postgres
volumes:
    volume_postgres:
      driver: local
    volume_pgadmin: