version: "3"
services:
  cubes-app:
    container_name: cubes-app
    build:
      context: .
      dockerfile: .Dockerfile
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://cubes:cubes76@postgres:5432/cubes_db
      NODE_ENV: development
      PORT: 3000
    ports:
      - "3000:3000"
  postgres:
    container_name: postgres
    image: postgres:10.4
    ports:
      - "5432:5432"
    volumes: 
      - ./postgresdata:/var/lib/postgresql/data
      - ./src/migrations/dbinit.sql:/docker-entrypoint-initdb.d/dbinit.sql
    restart: always
    environment:
      POSTGRES_USER: cubes
      POSTGRES_PASSWORD: cubes7676
      POSTGRES_DB: cubes_db
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:4.18
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: lefebvre@antadis.com
      PGADMIN_DEFAULT_PASSWORD: cubes76
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "8080:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      - postgres
volumes:
    db-data:
    pgadmin-data: